create table if not exists public.guest_submissions (
  id bigint generated by default as identity primary key,
  attendance_status text not null default 'attending',
  first_name text not null,
  last_name text not null,
  companion_first_name text,
  companion_last_name text,
  dietary_notes text,
  created_at timestamptz not null default now()
);

-- Safe migration for projects created with the first version of this site.
alter table public.guest_submissions
  add column if not exists attendance_status text not null default 'attending',
  add column if not exists dietary_notes text;

alter table public.guest_submissions
  drop constraint if exists guest_submissions_attendance_status_check;

alter table public.guest_submissions
  add constraint guest_submissions_attendance_status_check
  check (attendance_status in ('attending', 'not_attending'));

alter table public.guest_submissions enable row level security;

revoke all on table public.guest_submissions from anon;
grant insert on table public.guest_submissions to anon;

drop policy if exists "public can submit guest information" on public.guest_submissions;

create policy "public can submit guest information"
on public.guest_submissions
for insert
to anon
with check (
  attendance_status in ('attending', 'not_attending')
  and char_length(trim(first_name)) between 1 and 80
  and char_length(trim(last_name)) between 1 and 80
  and (
    attendance_status = 'not_attending'
    or (
      (companion_first_name is null and companion_last_name is null)
      or (
        char_length(trim(companion_first_name)) between 1 and 80
        and char_length(trim(companion_last_name)) between 1 and 80
      )
    )
  )
  and (dietary_notes is null or char_length(trim(dietary_notes)) between 1 and 300)
);

create index if not exists guest_submissions_created_at_idx
on public.guest_submissions (created_at desc);

create index if not exists guest_submissions_attendance_status_idx
on public.guest_submissions (attendance_status);
