create table if not exists public.guest_submissions (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  companion_first_name text,
  companion_last_name text,
  created_at timestamptz not null default now()
);

alter table public.guest_submissions enable row level security;

revoke all on table public.guest_submissions from anon;
grant insert on table public.guest_submissions to anon;

drop policy if exists "public can submit guest information" on public.guest_submissions;

create policy "public can submit guest information"
on public.guest_submissions
for insert
to anon
with check (
  char_length(trim(first_name)) between 1 and 80
  and char_length(trim(last_name)) between 1 and 80
  and (
    (companion_first_name is null and companion_last_name is null)
    or
    (
      char_length(trim(companion_first_name)) between 1 and 80
      and char_length(trim(companion_last_name)) between 1 and 80
    )
  )
);

create index if not exists guest_submissions_created_at_idx
on public.guest_submissions (created_at desc);
