create table if not exists public.guest_submissions (
  id bigint generated by default as identity primary key,
  attendance_status text not null default 'attending',
  first_name text not null,
  last_name text not null,
  companion_first_name text,
  companion_last_name text,
  seating_preferences text,
  message_to_couple text,
  song_request text,
  phone_number text,
  created_at timestamptz not null default now()
);

-- Safe migration for projects created with an earlier version of this site.
alter table public.guest_submissions
  add column if not exists attendance_status text not null default 'attending',
  add column if not exists seating_preferences text,
  add column if not exists message_to_couple text,
  add column if not exists song_request text,
  add column if not exists phone_number text;

-- Remove the obsolete dietary field after removing the legacy policy that referenced it.
drop policy if exists "public can submit guest information" on public.guest_submissions;

alter table public.guest_submissions
  drop column if exists dietary_notes;

alter table public.guest_submissions
  drop constraint if exists guest_submissions_attendance_status_check;

alter table public.guest_submissions
  add constraint guest_submissions_attendance_status_check
  check (attendance_status in ('attending', 'not_attending'));

alter table public.guest_submissions enable row level security;

revoke all on table public.guest_submissions from anon;
grant insert on table public.guest_submissions to anon;

create policy "public can submit guest information"
on public.guest_submissions
for insert
to anon
with check (
  attendance_status in ('attending', 'not_attending')
  and char_length(trim(first_name)) between 1 and 80
  and char_length(trim(last_name)) between 1 and 80
  and (
    attendance_status = 'not_attending'
    or (
      (companion_first_name is null and companion_last_name is null)
      or (
        char_length(trim(companion_first_name)) between 1 and 80
        and char_length(trim(companion_last_name)) between 1 and 80
      )
    )
  )
  and (
    attendance_status = 'not_attending'
    or (
      phone_number is not null
      and char_length(trim(phone_number)) between 7 and 30
    )
  )
  and (
    seating_preferences is null
    or char_length(trim(seating_preferences)) between 1 and 160
  )
  and (
    message_to_couple is null
    or char_length(trim(message_to_couple)) between 1 and 500
  )
  and (
    song_request is null
    or char_length(trim(song_request)) between 1 and 160
  )
  and (
    phone_number is null
    or char_length(trim(phone_number)) between 7 and 30
  )
);

create index if not exists guest_submissions_created_at_idx
on public.guest_submissions (created_at desc);

create index if not exists guest_submissions_attendance_status_idx
on public.guest_submissions (attendance_status);
